<a href="https://colab.research.google.com/github/eventia/mnistcode/blob/master/aicode08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 고등학교 수학과 파이썬으로 배우는 인공지능 소스코드  **Ch 8**

In [0]:
# 8.4	행렬계산을 위한 파이썬 코드 1

import numpy as np
from numpy.linalg import inv

A = np.array([[1,1],
              [2,3]])
B = np.array([[1100],
              [2800]])
invA = inv(A)
print(np.dot(invA , B))


[[500.]
 [600.]]


In [0]:
# 8.4	행렬계산을 위한 파이썬 코드 2

import numpy as np
# from numpy.linalg import inv

A = np.array([[1,1],
              [2,3]])
B = np.array([[1100],
              [2800]])
# inv(A) 대신 np.linalg.inv(A)
invA = np.linalg.inv(A) 
print(np.dot(invA , B))


[[500.]
 [600.]]


In [0]:
# 8.4	행렬계산을 위한 파이썬 코드 3

import numpy as np
from numpy.linalg import inv

A = np.array([[1,1,1,1],
              [5,2,4,7],
              [0,1,1,2],
              [5,2,2,3]])
B = np.array([[2350],
              [10600],
              [2450],
              [6800]])

invA = inv(A)
print(np.dot(invA, B))


[[500.]
 [550.]
 [700.]
 [600.]]


In [0]:
# 8.4	행렬계산을 위한 파이썬 코드 4

# 전치행렬
import numpy as np

# (1)행렬을 만들고
A = np.array([[1,1],
              [2,3]])

print("A = \n", A)
print("A.T = \n", A.T)  # (2)행렬이름 뒤에 .T 를 붙임


A = 
 [[1 1]
 [2 3]]
A.T = 
 [[1 2]
 [1 3]]


In [0]:
# 8.6	무작위 데이터로 신경망 함수 만들기

#00. keras 에서 mnist 데이터 읽어오기
import numpy as np
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 데이터 포맷은 60000,28,28 / 10000,28,28
# 데이터를 28x28 에서 784 로 변경
x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)

#01 Hidden 1 Layer : W, b 초기화 [W1, W2, B1, B2]
def init_mnistbw2(layer_x, layer_h, layer_y):
    matrix_nn = {}
    matrix_nn = dict(B1=np.random.rand(layer_h), 
                   B2=np.random.rand(layer_y), 
                   W1=np.random.rand(layer_x,layer_h), 
                   W2=np.random.rand(layer_h,layer_y))
    return matrix_nn

#02. 활성함수
def sigmoid(x):
    return 1 / (1+np.exp(-x))

#03. 소프트맥스
def softmax(X):
    X = X.T - np.max(X.T, axis=0)
    return (np.exp(X) / np.sum(np.exp(X), axis=0)).T

#04. predict
def predict(X):
    A = sigmoid(np.dot(X, W1) + B1)
    B = sigmoid(np.dot(A, W2) + B2)
    return softmax(B)

# process

ibw = init_mnistbw2(784,50,10)
W1, W2, B1, B2 = ibw['W1'], ibw['W2'], ibw['B1'], ibw['B2']
accuracy = 0

for i in range(len(x_test)):  # 10,000
    y = predict(x_test[i])
    p = np.argmax(y)
    if p == y_test[i]:
        accuracy = accuracy + 1

print("Acc = ", str(float(accuracy/len(x_test))))   # 0.1 근처의 값


Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step
Acc =  0.098
